const SUPABASE_URL='https://kzokretuuigjhxjzdlmk.supabase.co';
const KEY='sb_publishable_m8gAAZTKnOvCSWNvQijIXw_H1obE9vg';
const H={apikey:KEY,Authorization:`Bearer ${KEY}`};
let data={branches:[],categories:[],products:[],branchProducts:[],branch:null,cat:'all',q:'',lang:'ar'};
async function get(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:H});if(!r.ok)throw new Error(await r.text());return r.json()}
const $=s=>document.querySelector(s);
async function load(){try{const [b,c,p,bp]=await Promise.all([get('branches?select=id,name&order=id'),get('categories?select=id,name,active,website_visible,website_sort_order,sort_order&active=eq.true&website_visible=eq.true&order=website_sort_order.asc,sort_order.asc'),get('products?select=id,category_id,name,price,image_url,active,website_visible,website_sort_order&active=eq.true&website_visible=eq.true&order=website_sort_order.asc,name.asc'),get('branch_products?select=branch_id,product_id,active,price_override')]);data.branches=b;data.categories=c;data.products=p;data.branchProducts=bp;data.branch=b[0]?.id||null;render()}catch(e){$('#status').textContent='تعذر تحميل المنيو. تأكد من تشغيل SQL الخاص بالموقع.';console.error(e)}}
function render(){const ar=data.lang==='ar';document.documentElement.lang=ar?'ar':'en';document.documentElement.dir=ar?'rtl':'ltr';$('#langBtn').textContent=ar?'EN':'عربي';$('#heroTitle').textContent=ar?'اختار وجبتك المفضلة':'Choose your favorite meal';$('#heroText').textContent=ar?'الأسعار والصور متزامنة مباشرة مع نظام المطعم.':'Prices and photos are synced with the restaurant system.';$('#branchLabel').textContent=ar?'الفرع':'Branch';$('#search').placeholder=ar?'ابحث في المنيو...':'Search menu...';$('#footerText').textContent=ar?'منيو إلكتروني':'Digital Menu';
$('#branch').innerHTML=data.branches.map(x=>`<option value="${x.id}" ${String(x.id)===String(data.branch)?'selected':''}>${esc(x.name)}</option>`).join('');
$('#cats').innerHTML=`<button class="cat ${data.cat==='all'?'active':''}" data-cat="all">${ar?'الكل':'All'}</button>`+data.categories.map(c=>`<button class="cat ${String(data.cat)===String(c.id)?'active':''}" data-cat="${c.id}">${esc(c.name)}</button>`).join('');
const overrides=new Map(data.branchProducts.filter(x=>String(x.branch_id)===String(data.branch)).map(x=>[String(x.product_id),x]));let ps=data.products.filter(p=>{const o=overrides.get(String(p.id));if(o&&o.active===false)return false;if(data.cat!=='all'&&String(p.category_id)!==String(data.cat))return false;if(data.q&&!p.name.toLowerCase().includes(data.q.toLowerCase()))return false;return true});
$('#status').style.display='none';$('#products').innerHTML=ps.length?ps.map(p=>{const o=overrides.get(String(p.id));const price=o?.price_override??p.price;return `<article class="card"><div class="photo">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:'<div class="fallback">🍔</div>'}</div><div class="body"><h3>${esc(p.name)}</h3><div class="price">${Number(price).toFixed(0)} ${ar?'ج.م':'EGP'}</div></div></article>`}).join(''):`<div class="empty">${ar?'لا توجد أصناف مطابقة':'No matching items'}</div>`}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
document.addEventListener('click',e=>{if(e.target.matches('[data-cat]')){data.cat=e.target.dataset.cat;render()}if(e.target.id==='langBtn'){data.lang=data.lang==='ar'?'en':'ar';render()}});$('#branch').addEventListener('change',e=>{data.branch=e.target.value;render()});$('#search').addEventListener('input',e=>{data.q=e.target.value.trim();render()});load();
