const SUPABASE_URL='https://kzokretuuigjhxjzdlmk.supabase.co';
const KEY='sb_publishable_m8gAAZTKnOvCSWNvQijIXw_H1obE9vg';const H={apikey:KEY,Authorization:`Bearer ${KEY}`};
const $=s=>document.querySelector(s);let data={branches:[],categories:[],products:[],branchProducts:[],branch:null,cat:null,q:'',cart:[],selected:null};
async function get(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:H});if(!r.ok)throw new Error(await r.text());return r.json()}
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function priceFor(p){const o=data.branchProducts.find(x=>String(x.branch_id)===String(data.branch)&&String(x.product_id)===String(p.id));return Number(o?.price_override??p.price??0)}
function available(p){const o=data.branchProducts.find(x=>String(x.branch_id)===String(data.branch)&&String(x.product_id)===String(p.id));return !(o&&o.active===false)}
async function load(){try{const [b,c,p,bp]=await Promise.all([get('branches?select=id,name&order=id'),get('categories?select=id,name,active,website_visible,website_sort_order,sort_order&active=eq.true&website_visible=eq.true&order=website_sort_order.asc,sort_order.asc'),get('products?select=id,category_id,name,price,image_url,active,website_visible,website_sort_order&active=eq.true&website_visible=eq.true&order=website_sort_order.asc,name.asc'),get('branch_products?select=branch_id,product_id,active,price_override')]);data.branches=b;data.categories=c;data.products=p;data.branchProducts=bp;data.branch=b[0]?.id||null;renderAll()}catch(e){console.error(e);$('#categoryCards').innerHTML='<div class="empty">تعذر تحميل المنيو.</div>'}}
function renderAll(){renderBranch();renderCategories();renderCart()}
function renderBranch(){$('#branch').innerHTML=data.branches.map(x=>`<option value="${x.id}" ${String(x.id)===String(data.branch)?'selected':''}>${esc(x.name)}</option>`).join('')}
function catProducts(c){return data.products.filter(p=>String(p.category_id)===String(c.id)&&available(p))}
function renderCategories(){$('#categoryCards').innerHTML=data.categories.map(c=>{const ps=catProducts(c),img=ps.find(p=>p.image_url)?.image_url;return `<button class="category-card" data-open-cat="${c.id}">${img?`<img src="${esc(img)}" loading="lazy">`:'<div class="fallback">🍔</div>'}<div class="category-info"><b>${esc(c.name)}</b><small>${ps.length} عناصر</small></div></button>`}).join('')||'<div class="empty">لا توجد تصنيفات متاحة</div>'}
function openCategory(id){data.cat=String(id);$('#categoryView').classList.add('hidden');$('#productsView').classList.remove('hidden');renderProducts();scrollTo({top:0,behavior:'smooth'})}
function renderProducts(){const c=data.categories.find(x=>String(x.id)===String(data.cat));$('#categoryTitle').textContent=c?.name||'المنيو';$('#cats').innerHTML=data.categories.map(x=>`<button class="cat ${String(x.id)===String(data.cat)?'active':''}" data-open-cat="${x.id}">${esc(x.name)}</button>`).join('');let ps=data.products.filter(p=>available(p)&&(String(p.category_id)===String(data.cat))&&(!data.q||p.name.toLowerCase().includes(data.q.toLowerCase())));$('#status').style.display='none';$('#products').innerHTML=ps.length?ps.map(p=>`<article class="product-card" data-product="${p.id}"><div class="photo">${p.image_url?`<img src="${esc(p.image_url)}" loading="lazy">`:'<div class="fallback">🍔</div>'}</div><button class="plus" data-add="${p.id}">+</button><div class="product-body"><h3>${esc(p.name)}</h3><div class="price">${priceFor(p).toFixed(0)} ج.م</div></div></article>`).join(''):'<div class="empty">لا توجد أصناف مطابقة</div>'}
function openProduct(id){const p=data.products.find(x=>String(x.id)===String(id));if(!p)return;data.selected=p;$('#modalName').textContent=p.name;$('#modalPrice').textContent=`${priceFor(p).toFixed(0)} ج.م`;$('#modalImg').src=p.image_url||'';$('#modalImg').style.display=p.image_url?'block':'none';$('#modalNotes').value='';$('#productModal').classList.remove('hidden')}
function addSelected(){if(!data.selected)return;data.cart.push({key:Date.now()+Math.random(),product_id:data.selected.id,name:data.selected.name,price:priceFor(data.selected),qty:1,notes:$('#modalNotes').value.trim()});$('#productModal').classList.add('hidden');renderCart()}
function renderCart(){const count=data.cart.reduce((s,x)=>s+x.qty,0),total=data.cart.reduce((s,x)=>s+x.qty*x.price,0);$('#cartCount').textContent=count;$('#cartTotal').textContent=`${total.toFixed(0)} ج.م`;$('#cartModalTotal').textContent=`${total.toFixed(0)} ج.م`;$('#cartItems').innerHTML=data.cart.length?data.cart.map(x=>`<div class="cart-item"><div><b>${esc(x.name)}</b><small>${x.price.toFixed(0)} ج.م${x.notes?' • '+esc(x.notes):''}</small></div><div class="qty"><button data-minus="${x.key}">−</button><b>${x.qty}</b><button data-plus="${x.key}">+</button></div></div>`).join(''):'<div class="empty">السلة فاضية</div>'}
function qty(key,d){const x=data.cart.find(i=>String(i.key)===String(key));if(!x)return;x.qty+=d;if(x.qty<=0)data.cart=data.cart.filter(i=>i!==x);renderCart()}
document.addEventListener('click',e=>{const cat=e.target.closest('[data-open-cat]');if(cat)openCategory(cat.dataset.openCat);const add=e.target.closest('[data-add]');if(add){e.stopPropagation();openProduct(add.dataset.add)}const card=e.target.closest('[data-product]');if(card&&!add)openProduct(card.dataset.product);const close=e.target.closest('[data-close]');if(close)$('#'+close.dataset.close).classList.add('hidden');if(e.target.dataset.plus)qty(e.target.dataset.plus,1);if(e.target.dataset.minus)qty(e.target.dataset.minus,-1)});
$('#backBtn').onclick=()=>{$('#productsView').classList.add('hidden');$('#categoryView').classList.remove('hidden');data.q='';$('#search').value=''};$('#branch').onchange=e=>{data.branch=e.target.value;renderCategories();if(data.cat)renderProducts()};$('#searchBtn').onclick=()=>$('#searchBar').classList.toggle('hidden');$('#closeSearch').onclick=()=>$('#searchBar').classList.add('hidden');$('#search').oninput=e=>{data.q=e.target.value.trim();if($('#productsView').classList.contains('hidden')&&data.categories[0])openCategory(data.categories[0].id);renderProducts()};$('#addToCart').onclick=addSelected;$('#cartBar').onclick=()=>$('#cartModal').classList.remove('hidden');$('#checkoutBtn').onclick=()=>alert('السلة جاهزة. ربط إرسال الطلب للـ POS هو الخطوة التالية.');load();
