-- Top Burger Website V4 — secure website order intake + POS acceptance

create table if not exists public.website_orders (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete restrict,
  customer_name text not null,
  customer_phone text not null,
  delivery_address text not null,
  notes text,
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  accepted_order_id bigint references public.orders(id) on delete set null,
  accepted_at timestamptz,
  rejected_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.website_order_items (
  id bigint generated by default as identity primary key,
  website_order_id bigint not null references public.website_orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  variant_id bigint references public.product_variants(id) on delete set null,
  variant_name text,
  quantity integer not null check (quantity > 0 and quantity <= 20),
  unit_price numeric(12,2) not null,
  total numeric(12,2) not null,
  notes text
);

create table if not exists public.website_order_item_modifiers (
  id bigint generated by default as identity primary key,
  website_order_item_id bigint not null references public.website_order_items(id) on delete cascade,
  modifier_id bigint references public.modifiers(id) on delete set null,
  modifier_name text not null,
  price numeric(12,2) not null default 0
);

create index if not exists idx_website_orders_branch_status on public.website_orders(branch_id,status,created_at desc);
create index if not exists idx_website_order_items_order on public.website_order_items(website_order_id);

alter table public.website_orders enable row level security;
alter table public.website_order_items enable row level security;
alter table public.website_order_item_modifiers enable row level security;

revoke all on public.website_orders, public.website_order_items, public.website_order_item_modifiers from anon;
revoke all on public.website_orders, public.website_order_items, public.website_order_item_modifiers from authenticated;

grant select on public.website_orders, public.website_order_items, public.website_order_item_modifiers to authenticated;

drop policy if exists website_orders_staff_read on public.website_orders;
create policy website_orders_staff_read on public.website_orders
for select to authenticated
using (public.has_branch_access(branch_id));

drop policy if exists website_order_items_staff_read on public.website_order_items;
create policy website_order_items_staff_read on public.website_order_items
for select to authenticated
using (exists (
  select 1 from public.website_orders w
  where w.id=website_order_id and public.has_branch_access(w.branch_id)
));

drop policy if exists website_order_item_modifiers_staff_read on public.website_order_item_modifiers;
create policy website_order_item_modifiers_staff_read on public.website_order_item_modifiers
for select to authenticated
using (exists (
  select 1
  from public.website_order_items wi
  join public.website_orders w on w.id=wi.website_order_id
  where wi.id=website_order_item_id and public.has_branch_access(w.branch_id)
));

create or replace function public.submit_website_order(
  p_branch_id bigint,
  p_customer_name text,
  p_customer_phone text,
  p_delivery_address text,
  p_notes text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
  v_item jsonb;
  v_product record;
  v_variant record;
  v_modifier record;
  v_item_id bigint;
  v_qty integer;
  v_base numeric(12,2);
  v_unit numeric(12,2);
  v_subtotal numeric(12,2) := 0;
  v_variant_id bigint;
  v_mod_id bigint;
  v_has_variants boolean;
  v_name text;
  v_mod_ids bigint[];
begin
  if not exists(select 1 from public.branches where id=p_branch_id) then
    raise exception 'الفرع غير موجود';
  end if;
  if length(trim(coalesce(p_customer_name,''))) < 2 then raise exception 'اكتب اسم العميل'; end if;
  if length(regexp_replace(coalesce(p_customer_phone,''),'\D','','g')) < 8 then raise exception 'رقم الموبايل غير صحيح'; end if;
  if length(trim(coalesce(p_delivery_address,''))) < 5 then raise exception 'اكتب عنوان التوصيل'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'السلة فارغة'; end if;
  if jsonb_array_length(p_items) > 50 then raise exception 'عدد الأصناف كبير جدًا'; end if;

  insert into public.website_orders(branch_id,customer_name,customer_phone,delivery_address,notes)
  values(p_branch_id,trim(p_customer_name),trim(p_customer_phone),trim(p_delivery_address),nullif(trim(coalesce(p_notes,'')),''))
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1,least(20,coalesce((v_item->>'qty')::integer,1)));
    select p.id,p.name,p.price,p.active,p.website_visible
      into v_product
    from public.products p
    where p.id=(v_item->>'product_id')::bigint and p.active=true and p.website_visible=true;
    if not found then raise exception 'صنف غير متاح'; end if;
    if exists(select 1 from public.branch_products bp where bp.branch_id=p_branch_id and bp.product_id=v_product.id and bp.active=false) then
      raise exception 'صنف غير متاح في الفرع';
    end if;

    select exists(select 1 from public.product_variants pv where pv.product_id=v_product.id and pv.active=true) into v_has_variants;
    v_variant_id := nullif(v_item->>'variant_id','')::bigint;
    if v_has_variants then
      if v_variant_id is null then raise exception 'اختار الحجم'; end if;
      select pv.id,pv.name,pv.price into v_variant
      from public.product_variants pv
      where pv.id=v_variant_id and pv.product_id=v_product.id and pv.active=true;
      if not found then raise exception 'الحجم غير متاح'; end if;
      v_base:=v_variant.price; v_name:=v_product.name||' - '||v_variant.name;
    else
      v_base:=v_product.price; v_name:=v_product.name; v_variant_id:=null;
    end if;
    v_unit:=v_base;

    if jsonb_typeof(coalesce(v_item->'modifier_ids','[]'::jsonb))='array' then
      select coalesce(array_agg(distinct value::bigint),'{}'::bigint[]) into v_mod_ids
      from jsonb_array_elements_text(coalesce(v_item->'modifier_ids','[]'::jsonb));
      foreach v_mod_id in array v_mod_ids loop
        select m.id,m.name,m.price into v_modifier
        from public.modifiers m
        join public.product_modifiers pm on pm.modifier_id=m.id and pm.product_id=v_product.id
        where m.id=v_mod_id and m.active=true;
        if found then v_unit:=v_unit+v_modifier.price; end if;
      end loop;
    else v_mod_ids:='{}'::bigint[];
    end if;

    insert into public.website_order_items(website_order_id,product_id,product_name,variant_id,variant_name,quantity,unit_price,total,notes)
    values(v_order_id,v_product.id,v_name,v_variant_id,case when v_variant_id is null then null else v_variant.name end,v_qty,v_unit,v_unit*v_qty,nullif(trim(coalesce(v_item->>'notes','')),''))
    returning id into v_item_id;

    foreach v_mod_id in array v_mod_ids loop
      select m.id,m.name,m.price into v_modifier
      from public.modifiers m
      join public.product_modifiers pm on pm.modifier_id=m.id and pm.product_id=v_product.id
      where m.id=v_mod_id and m.active=true;
      if found then
        insert into public.website_order_item_modifiers(website_order_item_id,modifier_id,modifier_name,price)
        values(v_item_id,v_modifier.id,v_modifier.name,v_modifier.price);
      end if;
    end loop;
    v_subtotal:=v_subtotal+(v_unit*v_qty);
  end loop;

  update public.website_orders set subtotal=v_subtotal,total=v_subtotal where id=v_order_id;
  return jsonb_build_object('id',v_order_id,'code','WEB-'||lpad(v_order_id::text,5,'0'),'total',v_subtotal);
end;
$$;

revoke all on function public.submit_website_order(bigint,text,text,text,text,jsonb) from public;
grant execute on function public.submit_website_order(bigint,text,text,text,text,jsonb) to anon, authenticated;

create or replace function public.accept_website_order(p_website_order_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  w public.website_orders%rowtype;
  wi record;
  wm record;
  v_employee_id bigint;
  v_order_id bigint;
  v_order_item_id bigint;
  v_order_number text;
begin
  v_employee_id:=public.current_employee_id();
  if v_employee_id is null then raise exception 'المستخدم غير مربوط بموظف'; end if;
  select * into w from public.website_orders where id=p_website_order_id for update;
  if not found then raise exception 'طلب الموقع غير موجود'; end if;
  if not public.has_branch_access(w.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
  if w.status<>'pending' then raise exception 'تم التعامل مع الطلب بالفعل'; end if;

  insert into public.orders(branch_id,employee_id,customer_id,shift_id,order_type,payment_method,subtotal,discount,delivery_fee,total,status,source,customer_phone,customer_name,delivery_address,notes)
  values(w.branch_id,v_employee_id,null,null,'delivery','cash',w.subtotal,0,w.delivery_fee,w.total,'new','website',w.customer_phone,w.customer_name,w.delivery_address,w.notes)
  returning id into v_order_id;
  v_order_number:=w.branch_id||'-'||lpad(v_order_id::text,5,'0');
  update public.orders set order_number=v_order_number where id=v_order_id;

  for wi in select * from public.website_order_items where website_order_id=w.id order by id loop
    insert into public.order_items(order_id,product_id,product_name,quantity,unit_price,cost,total,notes)
    values(v_order_id,wi.product_id,wi.product_name,wi.quantity,wi.unit_price,coalesce((select cost from public.products where id=wi.product_id),0),wi.total,wi.notes)
    returning id into v_order_item_id;
    for wm in select * from public.website_order_item_modifiers where website_order_item_id=wi.id order by id loop
      insert into public.order_item_modifiers(order_item_id,modifier_id,modifier_name,price)
      values(v_order_item_id,wm.modifier_id,wm.modifier_name,wm.price);
    end loop;
  end loop;

  update public.website_orders set status='accepted',accepted_order_id=v_order_id,accepted_at=now() where id=w.id;
  return jsonb_build_object('order_id',v_order_id,'order_number',v_order_number);
end;
$$;

revoke all on function public.accept_website_order(bigint) from public;
grant execute on function public.accept_website_order(bigint) to authenticated;

create or replace function public.reject_website_order(p_website_order_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare w public.website_orders%rowtype;
begin
  select * into w from public.website_orders where id=p_website_order_id for update;
  if not found then raise exception 'طلب الموقع غير موجود'; end if;
  if not public.has_branch_access(w.branch_id) then raise exception 'ليس لديك صلاحية لهذا الفرع'; end if;
  if w.status<>'pending' then raise exception 'تم التعامل مع الطلب بالفعل'; end if;
  update public.website_orders set status='rejected',rejected_at=now() where id=w.id;
  return true;
end;
$$;

revoke all on function public.reject_website_order(bigint) from public;
grant execute on function public.reject_website_order(bigint) to authenticated;

notify pgrst, 'reload schema';
